config/routes.rb
SurveyBug::Application.routes.draw do
  
  resources :results
  
  resources :surveys do
    resources :results
    
    member do
      get 'take'
    end
  end
  
  
  root :to => 'surveys#index'

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :options
  belongs_to :survey
end

app/models/result.rb
class Result < ActiveRecord::Base
  belongs_to :survey
  
  validates :email, :presence => true
  validates :username, :presence => true
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions
  has_many :results
  
  attr_accessor :survey_data # For temporarily storing JSON data, allowing for a simple hidden field to take care of it.
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  # GET /results
  # GET /results.xml
  def index
    if params[:survey_id]
      @survey = Survey.find(params[:survey_id])
      @results = @survey.results
    else
      @results = Result.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @results }
    end
  end
  
  
  def create
    puts "Creating new Result for survey..."
    @result = Result.new(params[:result])
    @result.date = Time.now
    @survey = @result.survey
    
    @result.content = get_content_for_survey_result(@result, @survey, params)
    puts "Content: #{@result.content}"
    
    respond_to do |format|
      if @result.save
        format.html { redirect_to(@result, :notice => 'Thank you for participating!') }
      else
        format.html { render("surveys/take") }
        format.xml  { render :xml => @result.errors, :status => :unprocessable_entity }
      end
    end
  end
  

  # GET /results/1
  # GET /results/1.xml
  def show
    @result = Result.find(params[:id])
    @survey = @result.survey

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @result }
    end
  end


  # DELETE /results/1
  # DELETE /results/1.xml
  def destroy
    @result = Result.find(params[:id])
    @result.destroy

    respond_to do |format|
      format.html { redirect_to(results_url) }
      format.xml  { head :ok }
    end
  end
  
  private
  
    # This parses the form result into the content field of the result.
    # This could be extended in the future to store content in whatever format is desired, for example
    # using a key-value database store reference, or in XML format. For now we'll store as a nice formatted string.
    def get_content_for_survey_result(result, survey, params)
      #y params
      
      # Param format example:
      #   question-0-id: '13'
      #   question-0-text: How many pets do you have?
      #   question-0-value: '1'
      #   question-1-id: '14'
      #   question-1-text: What are your favorite foods?
      #   question-1-value-0: 'Cake'
      
      questions = Array.new
      question_params = params.reject{|k,v| !k.starts_with?("question-")}
      question_params.each do |k,v|
        keysplit = k.split("-")
        n = keysplit[1].to_i
        att = keysplit[2]
        questions[n] = Hash.new if questions[n].nil?
        qhash = questions[n]
        if att == "value"
          # Possible multiple values for checkbox, so use an array.
          qhash[att] = Array.new if !qhash.has_key?(att)
          qhash[att].push(v)
        else
          qhash[att] = v
        end
      end
      
      # Store a JSON-String
      ActiveSupport::JSON.encode(questions)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  # GET /surveys
  # GET /surveys.xml
  def index
    @surveys = Survey.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @surveys }
    end
  end

  # GET /surveys/1
  # GET /surveys/1.xml
  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @survey }
    end
  end
  
  # GET /surveys/1/take
  def take
    @survey = Survey.find(params[:id])
    @result = Result.new
    
    respond_to do |format|
      format.html # take.html.erb
    end
  end


  # GET /surveys/new
  # GET /surveys/new.xml
  def new
    @survey = Survey.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  # GET /surveys/1/edit
  def edit
    @survey = Survey.find(params[:id])
  end

  # POST /surveys
  # POST /surveys.xml
  def create
    @survey = Survey.new(params[:survey])

    respond_to do |format|
      if @survey.save
        format.html { redirect_to(:action => "edit", :id => @survey.id, :notice => 'Survey was successfully created.') }
        format.xml  { render :xml => @survey, :status => :created, :location => @survey }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /surveys/1
  # PUT /surveys/1.xml
  def update
    @survey = Survey.find(params[:id])
    success = @survey.update_attributes(params[:survey])
    
    puts "UPDATE: Survey:#{@survey.id} - #{@survey.name}"
    # Load the JSON Survey form data.
    survey_questions = ActiveSupport::JSON.decode(@survey.survey_data)
    #y survey_questions
    
    update_questions(@survey, survey_questions)
    
    # Render a response.
    respond_to do |format|
      if success
        format.html { redirect_to(@survey, :notice => 'Survey was successfully updated.') }
        format.xml  { head :ok }
        format.js { head :ok}
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
        format.js { render :json => @survey.errors, :status => :error }
      end
    end
  end

  # DELETE /surveys/1
  # DELETE /surveys/1.xml
  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to(surveys_url) }
      format.xml  { head :ok }
      format.js { render :text => "alert('Survey removed.')" }
    end
  end
  
  private
    def clean_existing_questions!(survey)
      survey.questions.each do |question|
        question.options.each do |opt|
          opt.destroy
        end
        question.destroy
      end
    end
    
    def update_questions(survey, json_questions)
      clean_existing_questions!(survey)
      json_questions.each_with_index do |json_question, i|
        question = Question.new(:survey => survey)
        question.text = json_question['text']
        question.kind = json_question['kind']
        question.order = i
        puts "[Creating Question] #{question.kind}, '#{question.text}'"
        question.save!
        json_question["options"].each_with_index do |json_opt, ii|
          option = Option.new(:question => question)
          option.text = json_opt
          option.order = ii
          puts "  [Option] #{option.text}"
          option.save!
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SurveyBug</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.js" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
	
<%= yield %>

</div>

<div id="footer">
	<%= link_to "Home", surveys_path %>	 
	| Created by <a href="mailto:trisweb@gmail.com">Tristan Harward</a> 
	for <a href="http://www.socialsci.com">SocialSci</a>
</div>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<h2>Listing results for <%= @survey.nil? ? "all surveys" : "\"#{@survey.name}\"" %></h2>

<table>
  <tr>
	<% if @survey.nil? %>
	<th>Survey Name (Click to Filter)</th>
	<% end %>
    <th>Date</th>
    <th>Name</th>
    <th>E-Mail</th>
    <th>Content</th>
    <th colspan="2">Actions</th>
  </tr>

<% @results.sort{|a,b| b.date <=> a.date }.each do |result| %>
  <%
	survey = @survey || result.survey
  %>
  <tr>
	<% if @survey.nil? %>
	<td>
		<% if result.survey %>
			<%= link_to result.survey.name, survey_results_path(result.survey) %>
		<% end %>
	</td>
	<% end %>
    <td width="125"><%= result.date.to_s(:short) %></td>
    <td><%= result.username %></td>
    <td><a href="mailto:<%= result.email %>"><%= result.email %></a></td>
    <td class="survey-result">
      <ol>
	  <%
		questions = ActiveSupport::JSON.decode(result.content.to_s)
		if questions
			questions.each_with_index do |q, i| 
	  %>
			  <li><strong><%= q["text"] %>:</strong> <%= q["value"].join(", ") %></li>
	  <% 
			end
		end 
	  %>
	  </ol>
    </td>
    <td class="action"><%= link_to 'View', result %></td>
    <td class="action"><%= link_to 'Remove', result, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<% if @survey %>
<p><strong><%= link_to "Take this Survey", take_survey_path(@survey) %></strong></p>
<p><strong><%= link_to "View All Results", results_path %></strong></p>
<% end %>

<p><%= link_to "< Back to Surveys", surveys_path %></p>

app/views/results/new.html.erb
<h1>New result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @result.date.to_s(:long) %>
</p>

<p>
  <b>Username:</b>
  <%= @result.username %>
</p>

<p>
  <b>Email:</b>
  <%= @result.email %>
</p>

<p>
  <b>Content:</b>
  <ol>
  <%
	questions = ActiveSupport::JSON.decode(@result.content)
	questions.each_with_index do |q, i| %>
	  <li><strong><%= q["text"] %><br /></strong> <%= q["value"].join(", ") %></li>
	<% end %>
  </ol>
</p>


<%= link_to '< Back to Surveys', surveys_path %>
<% if @survey %>
| <%= link_to 'See All Results for this Survey', survey_results_path(@survey) %>
<% end %>

app/views/surveys/_form.html.erb
<script type="text/javascript">
$(document).ready(function(){
	
	msg = $('.save_message');
	msg.css('opacity', 0);
	
	$('.edit_survey')
	.bind('ajax:before', function(){
		// Display "saving" in-progress status.
		survey_data = generateSurveyData();
		survey_data = JSON.stringify(survey_data);
		
		$("#survey_survey_data").attr("value", survey_data);
		msg.css('background-color', '#FFF6CC').html("Saving...").animate({opacity:1},200)
	})
	.bind('ajax:success', function(){
		// Flash the status.
		msg.css('background-color', '#CCFFCC').html("Saved!").delay(500).animate({opacity:0})
	})
	.bind('ajax:error', function(xhr, status, error){
		// Flash the error and keep it up until re-submitted.
		msg.css('background-color', '#FFCCCC').html("Error: "+status.statusText).css('opacity', 1)
	})
	.bind('ajax:complete', function(){
		// Clean-up if needed.
	});
	
	$('#survey_name').keyup(function(e) {
		// Update the title of the page.
		$('#edit_title').html("Editing survey \""+$('#survey_name').attr("value")+"\"");
	});

});
</script>

<% is_new_form = defined?(new_form) && new_form %>

<%= form_for(@survey, :remote => !is_new_form) do |f| %>
  <div class="save_message">x</div>
  <% if @survey.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@survey.errors.count, "error") %> occurred during save:</h2>
      <ul>
      <% @survey.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :survey_data %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, :size => 70 %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 4, :cols => 65 %>
  </div>

  <div class="actions">
    <%= f.submit "Save Survey", :disable_with => "Saving...", :class => "submit_button" %>
  </div>

  <% if !is_new_form %>
    <%= render "survey_editor" %>

	<div class="actions">
		<%= f.submit "Save Survey", :disable_with => "Saving...", :class => "submit_button" %>
	</div>

  <% end %>



  <div class="save_message">x</div>
<% end %>

app/views/surveys/_survey_editor.html.erb
<script type="text/javascript">
	$(document).ready(function() {
		$("#survey_questions" ).sortable({opacity:0.75});
		$(".survey-question-options").sortable({opacity:0.75, items: 'div'});
		
		$(".new-option-box").focusin(function(e) { e.target.value = "" });
		$(".new-option-box").focusout(function(e) { e.target.value = "Add new option..." });
		
		// Somewhat complicated way to detect an "Enter" keypress, and find the next
		// text field to focus. Allows for quick entry of Options by pressing enter to create a new option.
		$(".option-text,.new-option-box,.question-text").keypress(function(e) {
		    if (e.keyCode == 13) {
				foundSelf = false;
				elements = $("#survey_questions").find(".option-text,.new-option-box,.question-text");
				if (e.shiftKey) {
					elements = $(elements.toArray().reverse());
				}
				elements.each(function(i, item) {
					if (foundSelf) {
						$(item).focus();
						return false;
					} else if (item == e.target) {
						foundSelf = true;
					}
				});
		        e.preventDefault();
				return false;
		    }
		});
		
		// If a user types in the New Option field, create a new option and transfer them to it.
		$(".new-option-box").keyup(function(e) { 
			// Create a new item, copy that first character, and focus on it. Seamless.
			if (e.target.value) {
				newOption = $("#new_option_template").clone(true);
				newOption.removeAttr("id");
				$(e.target).before(newOption);
				optionText = newOption.find(".option-text");
				optionText.attr("value", e.target.value);
				$(".survey-question-options").sortable({opacity:0.75, items: 'div'});
				$(".survey-question-options").sortable("refresh")
				optionText.focus();
			}
		});
		
		// Add event handlers.
		
		$("#add_question_button").click(addQuestion);
		$(".remove-option-button").click(removeOption);
		$(".remove-question-button").click(removeQuestion);
	});
	
	// END Document.ready. Begin function definitions.
	
	function addQuestion(event) {
		newQuestion = $("#new_question_template").clone(true);
		newQuestion.removeAttr("id");
		newQuestion.appendTo($('#survey_questions'));
		newQuestion.find(".question-text").focus();
		$(".survey-question-options").sortable({opacity:0.75, items: 'div'});
	}
	
	
	// Remove an option for a given question (called on press of red X button next to option)
	function removeOption(event) {
		event.target.parentNode.parentNode.removeChild(event.target.parentNode);
	}
	
	
	// Remove an entire question (called on press of red X button next to Question title)
	// Confirms removal.
	function removeQuestion(event) {
		if (confirm("Are you sure you want to remove this Question?")) {
			event.target.parentNode.parentNode.removeChild(event.target.parentNode);
		}
	}
	
	
	// Serialize the survey data and place in hidden field for automatic AJAX transfer.
	function generateSurveyData() {
		survey_data = []
		// Wrap it all up in JSON to be sent. Place in hidden field 'survey_data', in the parent page.
		$("#survey_questions").children(".survey-question").each(function(i, question) {
			question_obj = {}
			question_obj['text'] = $(question).find('.question-text').first().attr('value');
			question_obj['kind'] = $(question).find('.question-kind').first().attr('value');
			question_obj['options'] = $(question).find('.option-text').map(function(i, obj) { return obj.value; }).toArray();
			survey_data.push(question_obj);
		});
		return survey_data;
	}
	
</script>

<div id="surveyeditor">
	<h3>Questions:</h3>
	
	<p><em>Tip: Use Enter and Shift+Enter to navigate between options and questions.</em></p>
	
	<div id="survey_questions">
		<%
			# Iterate through the questions for this survey
			# The survey-editor javascript is based directly on the DOM structure, so no separate data structure is required.
			# What is displayed is always exactly what gets sent.
			
			@survey.questions.sort{|a,b| a.order <=> b.order}.each do |question|
		%>
			<div class="survey-question">
				<span class="drag-handle"></span>
				<input class="question-text" type="text" size="50" name="question-<%= question.id %>-name" value="<%= question.text %>" />
				
				<select name="question-kind" class="question-kind">
					<option value="radio"<%= question.kind == 'radio' ? ' selected="selected"' : ""%>>Radio Button</option>
					<option value="checkbox"<%= question.kind == 'checkbox' ? ' selected="selected"' : ''%>>Checkbox</option>
				</select>
				
				<input type="button" value="x" class="remove-question-button" tabindex="0">
				
				<div class="survey-question-options">
					<% question.options.sort{|a,b| a.order <=> b.order}.each do |option| %>
						<div class="survey-question-option">
							<span class="drag-handle-sm"></span>
							<input type="text" size="40" value="<%= option.text %>" class="option-text" />
							<input type="button" value="x" class="remove-option-button" tabindex="0">
						</div>
					<% end %>
					<input type="text" size="40" value="Add new option..." class="new-option-box">
				</div>
				
			</div>
		<%
			end
		%>
	</div>
	
	<!-- 
	The following templates will be copied to create new elements. 
	I'll admit this is messy and duplicated code - ideally it should be the same HTML above in the 
	iteration, and below for empty items. 
	
	One possibility is creating common JS that loads the initial DIVs using the same method
	as the dynamic creation on the client. 
	
	Another option would be to just use a common rails method parameterized to create both the initial 
	DIVs and the empty templates.
	
	Option 2 is probably best as it relies less on the client javascript, and the HTML would always be 
	consistent.
	-->
	
	<div id="survey_item_templates">
		<div class="survey-question" id="new_question_template">
			<span class="drag-handle"></span>
			<input type="text" size="50" name="question-new-name" value="" class="question-text" />
			<select name="question-kind" class="question-kind">
				<option value="radio">Radio Button</option>
				<option value="checkbox">Checkbox</option>
			</select>
			<input type="button" value="x" class="remove-question-button">
			
			<div class="survey-question-options">
				<input type="text" size="40" value="Add new option..." class="new-option-box">
			</div>
		</div>
		
		<div class="survey-question-option" id="new_option_template">
			<span class="drag-handle-sm"></span>
			<input type="text" size="40" value="" class="option-text" />
			<input type="button" value="x" class="remove-option-button" />
		</div>
	</div>
	
	
	<input type="button" id="add_question_button" value="+ Add a Question" />
</div>

app/views/surveys/_take_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result && @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> occurred during save:</h2>
      <ul>
      <% @result.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :survey_id, :value => @survey.id %>

  <div class="field largefield">
    <%= f.label :username, "Full Name" %><br />
    <%= f.text_field :username, :size => 55 %>
  </div>
  <div class="field largefield">
    <%= f.label :email, "E-Mail Address" %><br />
    <%= f.text_field :email, :size => 55 %>
  </div>

	<!-- Generally this shares the list style with the edit page, since they share the same structure. -->
	<div id="survey_questions" class="take_survey">
		<%
			# Iterate through the questions for this survey
			@survey.questions.sort{|a,b| a.order <=> b.order}.each_with_index do |question, i|
		%>
			<input type="hidden" name="question-<%=i%>-id" value="<%= question.id %>" />
			<input type="hidden" name="question-<%=i%>-text" value="<%= question.text %>" />
			<div class="survey-question">
				<strong><%= i+1 %>.</strong> <%= question.text %>

				<div class="survey-question-options">
					<% question.options.sort{|a,b| a.order <=> b.order}.each_with_index do |option, ii| 
						fieldname = "question-#{i}-value" + (question.kind == "checkbox" ? "-#{ii}" : '')
						%>
						<input type="<%= question.kind %>" value="<%= option.text %>" id="<%= fieldname+ii.to_s %>" name="<%= fieldname %>"<%= params[fieldname] == option.text ? " checked='checked'" : "" %>>
						<label for="<%= fieldname+ii.to_s %>"><%= option.text%></label><br />
					<% end %>
				</div>
				
			</div>
		<%
			end
		%>
	</div>


  <div class="actions">
    <%= f.submit "Submit Survey", :class => "submit_button" %>
  </div>

<% end %>

app/views/surveys/edit.html.erb
<h1 id="edit_title">Editing survey "<%= @survey.name %>"</h1>

<p>Survey URL to send to friends: <strong><%= take_survey_url(@survey) %></strong></p>

<%= render 'form' %>


<p><strong><%= link_to 'Take this survey!', take_survey_path(@survey) %></strong></p>

<%= link_to 'View', @survey %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/index.html.erb
<h1>SurveyBug</h1>
<h2>Create surveys and collect results quickly and easily!</h2>

<h3><%= link_to 'Create a New Survey', new_survey_path %></h3>

<hr />

<h3>Available Surveys:</h3>

<table class="survey_list">
  <tr>
    <th>Name (Click to Take!)</th>
    <th>Description</th>
    <th colspan="4">Actions</th>
  </tr>

<% @surveys.each do |survey| %>
  <tr>
    <td width="25%"><strong><%= link_to survey.name, take_survey_path(survey) %></strong></td>
    <td width="50%"><%= survey.description %></td>
	<td class="action"><%= link_to 'Take', take_survey_path(survey) %></td>
    <td class="action"><%= link_to 'Edit', edit_survey_path(survey) %></td>
	<td class="action"><strong><%= link_to 'Results', survey_results_path(survey) %></strong></td>
    <td class="action"><%= link_to 'Remove', survey, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<p><%= link_to 'Create New Survey', new_survey_path %></p>

<p><%= link_to 'View Results for All Surveys', results_path %>

app/views/surveys/new.html.erb
<h1>New survey</h1>

<%= render 'form', :new_form => true %>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>

<p>
  <b>Description:</b>
  <%= @survey.description %>
</p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back', surveys_path %>

app/views/surveys/take.html.erb
<h2>Take Survey "<%= @survey.name %>"</h2>

<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @survey.name %>
</p>

<p>
  <%= @survey.description %>
</p>

<hr />

<%= render 'surveys/take_form' %>

<hr />

<p>Want to send this survey to your friends? Send them this URL: <strong><%= take_survey_url(@survey) %></strong></p>


<%= link_to 'Edit', edit_survey_path(@survey) %> |
<%= link_to 'Back to List', surveys_path %>